version: '3.8'

services:
  bot:
    build: .
    container_name: discord-chores-bot
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    environment:
      - TZ=Europe/Bratislava